version: '2'
services:
  opa:
    image: openpolicyagent/opa:0.6.0
    ports:
      - 8181:8181
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
  api_server:
    ports:
      - 5020:5020
    environment:
      - OPA_ADDR=http://opa:8181
      - POLICY_PATH=/v1/data/httpapi/authz
